---
abstract: 'build web sites from markdown files'
author:
  - 'Mirko Westermeier <mail@memowe.de>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Contenticious
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 1.08
  File::Basename: 2.76
  File::Copy::Recursive: 0.38
  File::Path: 2.04
  FindBin: 1.49
  List::Util: 1.19
  Mojolicious: 3.40
  Mojolicious::Plugin::RelativeUrlFor: 0.01
  Mojolicious::Plugin::Subdispatch: 0.03
  Text::Markdown: 1.000031
  perl: 5.010001
resources:
  bugtracker: http://github.com/memowe/contenticious/issues
  homepage: http://memowe.github.com/contenticious/
  repository: http://github.com/memowe/contenticious
version: 0.331
